#!/bin/bash

# Script para visualizar la estructura del proyecto creado

echo "📁 Estructura Final del Proyecto NestJS Professional"
echo "=================================================="
echo ""

echo "📂 SRC - Código Backend (MVC)"
echo "├── main.ts (Seguridad: Helmet, CORS, Validación Global)"
echo "├── app.module.ts (Módulo raíz con ConfigModule + TypeORM)"
echo "├── config/"
echo "│   ├── database.config.ts (Configuración PostgreSQL - TypeORM)"
echo "│   ├── security.config.ts (JWT + CORS)"
echo "│   └── index.ts"
echo "└── modules/users/ (Ejemplo MVC Completo)"
echo "    ├── controllers/users.controller.ts (6 endpoints CRUD)"
echo "    ├── services/users.service.ts (Validaciones, hash, DTOs)"
echo "    ├── entities/user.entity.ts (Modelo TypeORM)"
echo "    ├── dtos/"
echo "    │   ├── create-user.dto.ts (@IsEmail, @MinLength)"
echo "    │   ├── update-user.dto.ts"
echo "    │   ├── user-response.dto.ts"
echo "    │   └── index.ts"
echo "    └── users.module.ts (Importa TypeORM + ReportsService)"
echo ""

echo "🔧 Configuración"
echo "├── .env.example (19 variables de entorno)"
echo "├── .eslintrc.js (Reglas TypeScript + Prettier)"
echo "├── .prettierrc (100 chars, 2 espacios, trailing commas)"
echo "├── package.json (Scripts + 25+ dependencias NestJS)"
echo "├── tsconfig.json (Strict mode, decorators)"
echo "├── tsconfig.build.json"
echo "├── nest-cli.json"
echo "└── .gitignore"
echo ""

echo "🐳 Docker & Local Dev"
echo "├── Dockerfile (Multi-stage, healthcheck, non-root user)"
echo "├── docker-compose.yml (API + PostgreSQL stack)"
echo ""

echo "🔄 CI/CD Pipeline (GitHub Actions)"
echo "└── .github/workflows/ci-cd.yml"
echo "    └── 5 Stages:"
echo "        1️⃣ Install & Lint (npm, ESLint, Prettier)"
echo "        2️⃣ Test (Jest + PostgreSQL service)"
echo "        3️⃣ SonarQube (Análisis de código + Quality Gate)"
echo "        4️⃣ Build (Compile + Docker → GHCR)"
echo "        5️⃣ Deploy (solo develop/main → Kubernetes)"
echo ""

echo "☸️  Kubernetes Manifests (Production Ready)"
echo "├── k8s/namespace.yaml (staging + production)"
echo "├── k8s/configmap-secret.yaml (Config + Secrets)"
echo "├── k8s/deployment.yaml (3 replicas, probes, security)"
echo "├── k8s/service.yaml (ClusterIP)"
echo "├── k8s/hpa.yaml (Auto-scaling 3-10 pods)"
echo "├── k8s/network-policy.yaml (Ingress/Egress controlado)"
echo "└── k8s/pod-disruption-budget.yaml (Min 2 pods)"
echo ""

echo "🏗️  Terraform - IaC AWS EKS"
echo "├── terraform/provider.tf (AWS provider + default tags)"
echo "├── terraform/variables.tf (Región, tamaño cluster, etc.)"
echo "├── terraform/outputs.tf (Cluster ID, endpoint, kubectl)"
echo "├── terraform/backend.tf (S3 state storage)"
echo "├── terraform/vpc.tf (VPC 10.0.0.0/16 + 3 subnets)"
echo "├── terraform/iam.tf (Roles para cluster + workers)"
echo "├── terraform/eks.tf (EKS Cluster + Node Group)"
echo "└── terraform/README.md (Instrucciones terraform)"
echo ""

echo "🧪 Tests"
echo "└── test/"
echo "    ├── app.module.ts (Test module setup)"
echo "    └── users.controller.e2e.spec.ts (Ejemplos tests)"
echo ""

echo "📚 Documentación"
echo "└── README.md (2500+ líneas, todo explicado)"
echo ""

echo "=================================================="
echo "✅ TOTAL: ~35 archivos creados"
echo ""
echo "🚀 Quick Start:"
echo "  1. cp .env.example .env"
echo "  2. npm install"
echo "  3. docker-compose up -d"
echo "  4. npm run start:dev"
echo "  5. Swagger: http://localhost:3000/api/docs"
echo ""
